[tool.poetry]
name = "grafive"
version = "0.1.0"
description = ""
authors = ["Torres <jocta.torres@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
